name: Laravel Pint
on: pull_request
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@9258dcb4bb75f0c158f78fea0e10b002bf65e957
          with:
            preset: laravel
            verboseMode: true
            pintVersion: 1.2.1
