name: Laravel Pint
on: pull_request
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@14b329e0e2d3dcd56f47ed5403b41f91af0b2e35
          with:
            preset: laravel
            testMode: true
            verboseMode: true
