name: Laravel Pint
on: pull_request
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@18945b813caa22e3c01057062ca73dc099dbe194
          with:
            preset: laravel
            verboseMode: true
            pintVersion: 1.2.1
